### ISSUE TITLE
ERROR: DROPPED LINE from tcollector

### ISSUE THREAD

**Issue by gsaray101** [OpenTSDB/tcollector#200] opened 2015-03-13 16:08 UTC
Hi Team:

I am running Tcollector framework to send data to OpenTSDB. I am seeing a lot of these lines in the tcollector.log file:

tcollector[6984] ERROR: DROPPED LINE

When I look at the OpenTSDB log, I do see these:

12:06:34.269 DEBUG [CompactionQueue.run] flush() took 7ms, new queue size=255268 (-1426)
12:06:44.279 DEBUG [CompactionQueue.run] flush() took 9ms, new queue size=253850 (-1418)
12:06:54.288 DEBUG [CompactionQueue.run] flush() took 7ms, new queue size=252573 (-1411)
12:07:04.302 DEBUG [CompactionQueue.run] flush() took 14ms, new queue size=251306 (-1403)
12:07:14.310 DEBUG [CompactionQueue.run] flush() took 8ms, new queue size=249910 (-1396)
12:07:24.317 DEBUG [CompactionQueue.run] flush() took 6ms, new queue size=248527 (-1388)
12:07:34.325 DEBUG [CompactionQueue.run] flush() took 7ms, new queue size=247147 (-1380)
12:07:44.334 DEBUG [CompactionQueue.run] flush() took 9ms, new queue size=245849 (-1373)

Is Drop line occuring because of high ques on OpenTSDB? How do you address this problem? Please help.

**Comment by vasiliyk** [comment] 2015-04-06 08:15
When you see "ERROR: DROPPED LINE" in tcollector log it means READ queue is full.

Tcollector constantly queries collectors and add data to READ queue when it can't send datapoint to backend for a long time (network problem, opentsdb server is not available, etc) queue reaches max length and tcollector drop new datapoints.

Also there is the MAX_READQ_SIZE = 100000 entry which set size of READ queue in tcollector.py and sometimes you may want to tune it.

**Comment by jaredledvina** [comment] 2016-01-24 07:28
Typically, I've seen that restarting tcollector in these cases will correct the issue. However, I also believe that drops everything that was in the READ queue and use lose all that data. Not ideal... if there's a way to restart tcollector's connection to OpenTSDB I'd love to know. 

Is it possible this is caused by using an ELB between tcollector and OpenTSDB? I'm not sure why we have nodes that get in this state...

**Comment by johann8384** [comment] 2016-02-01 21:43
TCollector will periodically try to re-connect, you can also use the -L option to specify multiple hosts to connect to. I used to do DNS RR and/or an HAProxy LB as the destination for TCollector in my networks. Now I just use -L and the set of real servers that were behind the LB or DNS RR. This allows TCollector to balance where it sends metrics to as well as retry other hosts if one node becomes unreachable.

I don't think there is actually an issue with TCollector here. I am going to close this, feel free to re-open with more details if you believe I am incorrect.

**Closed by johann8384** 2016-02-01 21:43 UTC
